
#Sound that is played when resetting rank
reset-sound: BAT_TAKEOFF
#Sound that is played when unable to set a rank
reset-sound-error: NOTE_BASS


#Disable if using any chat plugin.
chat: true
#Server chat format
chat-format: "<rank><player> &7>> &r<message>"

progress-bar:
  bar: "\u25A0"
  size: 10
  color-1: "&a"
  color-2: "&7"
#Welcome message for player
join-message:
  #Set true if you want the welcome message to be sent only on the first login.
  first-join: false
  #Set to true if you want the player's chat to be cleared when joining.
  clear-chat: true
  #Welcome message, it has support for PlaceholdersAPI
  message:
    - ''
    - '&e================={ &6Hypixel &e}================='
    - '      &eHi <player>, welcome to our server.'
    - '&emake friends and build your empire on the server.'
    - '     &ebecome the strongest and most feared.'
    - '&e==========================================='
    - ' '